### ISSUE TITLE
Support for Outlook 2016

### ISSUE THREAD

**Issue by MaxWilson** [mmanela/MarkdownOutlook#26]
Would it be possible to port MarkdownOutlook to work with Office 365 (Outlook 2016)?

**Comment by DGSephiro** [comment]
Not that I have tried, but does this request infer that it does not function in Outlook 2016?

**Comment by Xapphire13** [comment]
What works for me

* Installation
* Showing in the ribbon
* Markdown preview

What **doesn't** work for me

* Sending rendered mails (they send in raw format)

**Comment by gerardbosch** [comment]
It looks that in my case is **working fine** in Outlook 2016. I used release v1.0.2 of the plug-in. The html is not actually rendered in the compose window (but you can click the "Show preview" button to check the results), but when the mail is sent, it is actually rendered to html.

I would like to ask, how can we customize how is html rendered? For example to define something like this to limit the line length and improve readability: `max-width: 78ex;`

```css
p {
  max-width: 78ex;
}
```

or similary, is it possible to configure the font and size for the rendered html? Thanks!

**Comment by mmanela** [comment]
It shouldn't be a big change to make it work, I just don't have the time to build and test this. But I will gladly take PRs

**Comment by SturmB** [comment]
Sadly, v1.0.2 does not work on Outlook 2016:

![OUTLOOK_85yTiORDNU](https://user-images.githubusercontent.com/6216224/66131389-5809d900-e5c1-11e9-8fca-b7ae2d23567a.png)

The `Details` button reveals:
```
Name: MarkdownOutlook - MarkdownOutlook
From: file:///C:/Users/<username>/AppData/Roaming/Markdown Outlook/Markdown Outlook/MarkdownOutlook.vsto

************** Exception Text **************
System.Security.SecurityException: Customized functionality in this application will not work because the certificate used to sign the deployment manifest for MarkdownOutlook or its location is not trusted. Contact your administrator for further assistance.
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInTrustEvaluator.VerifyTrustPromptKeyInternal(ClickOnceTrustPromptKeyValue promptKeyValue, DeploymentSignatureInformation signatureInformation, String productName, TrustStatus status)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInTrustEvaluator.VerifyTrustUsingPromptKey(Uri manifest, DeploymentSignatureInformation signatureInformation, String productName, TrustStatus status)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInTrustEvaluator.VerifyTrustUsingPromptKey(Uri manifest, DeploymentSignatureInformation signatureInformation, String productName)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.ProcessSHA1Manifest(ActivationContext context, DeploymentSignatureInformation signatureInformation, PermissionSet permissionsRequested, Uri manifest, ManifestSignatureInformationCollection signatures, AddInInstallationStatus installState)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.VerifySecurity(ActivationContext context, Uri manifest, AddInInstallationStatus installState)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()
The Zone of the assembly that failed was:
MyComputer
```

**Comment by tylvn** [comment]
It seems has some warning from Microsoft Office about inability of verify developer.

<img width="436" alt="image" src="https://user-images.githubusercontent.com/95011132/163804230-6267fd30-7e1d-4865-8304-c347701ad55d.png">

This windows warn below.

> Although Office customization items can be useful, they can be harmful to your computer. If you do not trust their source, do not install this software.
